export const CHANNELS = {
  ['VOTE']: 'VOTE',
  ['LEADERBOARD']: 'LEADERBOARD',
  ['PLAYERS']: 'PLAYERS',
  ['TIMER']: 'TIMER',
};

export const EVENTS = {
  ['EMOJI_CLICKED']: 'EMOJI_CLICKED',
  ['EMOJI_SELECTION_RECORDED']: 'EMOJI_SELECTION_RECORDED',
  ['PLAYER_JOINED']: 'PLAYER_JOINED',
  ['TICK']: 'TICK',
  ['ROUND_STARTED']: 'ROUND_STARTED',
  ['ROUND_ENDED']: 'ROUND_ENDED',
};

export const ROUNDS = {
  DURATION: 15,
};
