export const CHANNELS = {
  ['VOTE']: 'VOTE',
  ['LEADERBOARD']: 'LEADERBOARD',
  ['PLAYERS']: 'PLAYERS',
};

export const EVENTS = {
  ['EMOJI_CLICKED']: 'EMOJI_CLICKED',
  ['EMOJI_SELECTION_RECORDED']: 'EMOJI_SELECTION_RECORDED',
  ['PLAYER_JOINED']: 'PLAYER_JOINED',
};
