export enum RoundActions {
  START = 'START',
  END = 'END',
  RESET = 'RESET',
  STEP = 'STEP',
  HYDRATE = 'HYDRATE',
  SHOW_ROUND_SUMMARY = 'SHOW_ROUND_SUMMARY',
  HIDE_ROUND_SUMMARY = 'HIDE_ROUND_SUMMARY',
  REFRESH_ROUND_FROM_SERVER = 'REFRESH_ROUND_FROM_SERVER',
}
